# Generated by Django 4.2.3 on 2023-08-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_state_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='state_tb',
        ),
    ]
